# Generated by Django 5.2.7 on 2025-12-10 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AppLSD', '0051_frequenciaatividade_criado_em_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('IDOSOS', 'Grupo de Idosos'), ('GESTANTES', 'Grupo de Gestantes'), ('ADOLESCENTES', 'Grupo de Adolescentes'), ('MISTO', 'Grupo Misto')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('PARTICIPANTE', 'Participante'), ('ACOMPANHANTE', 'Acompanhante'), ('RESPONSAVEL', 'Responsável')], default='PARTICIPANTE', max_length=20)),
                ('attendance_status', models.CharField(choices=[('INSCRITO', 'Inscrito'), ('PRESENTE', 'Presente'), ('FALTOU', 'Faltou'), ('JUSTIFICADO', 'Justificado')], default='INSCRITO', max_length=20)),
                ('group_label', models.CharField(blank=True, help_text='Idoso / Gestante / Adolescente', max_length=20, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='events.event')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_participations', to='AppLSD.person')),
            ],
            options={
                'unique_together': {('event', 'person')},
            },
        ),
    ]
