# Generated by Django 5.2.7 on 2025-12-13 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='area_atuacao',
            field=models.CharField(blank=True, choices=[('SOCIOEDUCATIVA', 'Socioeducativa'), ('CULINÁRIA', 'Culinária'), ('ESPORTE_LAZER', 'Esporte e Lazer'), ('ARTE_CULTURA', 'Arte e Cultura'), ('QUALIFICACAO_PROFISSIONAL', 'Qualificação Profissional')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='partner_organization',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='setor_responsible',
            field=models.CharField(blank=True, choices=[('SERVIÇO_SOCIAL', 'Serviço Social'), ('SEMDeS', 'SEMDES'), ('SERVIÇO_ASSISTÊNCIA', 'Serviço de Assistência'), ('FEJA', 'FEJA')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
