# Generated by Django 5.2.7 on 2025-12-13 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_area_atuacao_event_partner_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('IDOSOS', 'Grupo de Idosos'), ('GESTANTES', 'Grupo de Gestantes'), ('ADOLESCENTES', 'Grupo de Adolescentes'), ('TERCEIRO SÁBADO', 'Evento Terceiro Sábado')], max_length=20),
        ),
    ]
