# Generated by Django 5.2.7 on 2025-12-14 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_event_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventparticipant',
            name='notes',
        ),
    ]
