# Generated by Django 5.2.7 on 2025-12-14 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_remove_eventparticipant_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventparticipant',
            name='group_label',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
