# Generated by Django 5.2.7 on 2025-12-14 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_eventparticipant_group_label'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventparticipant',
            unique_together=set(),
        ),
    ]
