# Generated by Django 5.2.7 on 2025-12-10 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='descricao',
            new_name='atividade',
        ),
        migrations.RenameField(
            model_name='turma',
            old_name='professor',
            new_name='educadora',
        ),
    ]
