# Generated by Django 5.2.5 on 2025-09-24 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(default='', max_length=100)),
                ('responsible_name', models.CharField(default='', max_length=255)),
                ('nis', models.CharField(blank=True, max_length=20, null=True)),
                ('rg', models.CharField(blank=True, max_length=20, null=True)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, max_length=10, null=True)),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('neighborhood', models.CharField(default='Não informado', max_length=100)),
                ('reference_point', models.CharField(blank=True, max_length=200, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('marital_status', models.CharField(blank=True, max_length=30, null=True)),
                ('education', models.CharField(blank=True, max_length=50, null=True)),
                ('race', models.CharField(blank=True, max_length=30, null=True)),
                ('religion', models.CharField(blank=True, max_length=50, null=True)),
                ('social_benefits', models.CharField(blank=True, max_length=100, null=True)),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('has_proven_income', models.BooleanField(default=False)),
                ('min_salary_1', models.BooleanField(default=False)),
                ('min_salary_2', models.BooleanField(default=False)),
                ('others_contribute', models.BooleanField(default=False)),
                ('who_contributes', models.CharField(blank=True, max_length=100, null=True)),
                ('num_residents', models.IntegerField(default=0)),
                ('has_elderly', models.BooleanField(default=False)),
                ('has_adolescent', models.BooleanField(default=False)),
                ('has_child', models.BooleanField(default=False)),
                ('has_pregnant', models.BooleanField(default=False)),
                ('file_info', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, default='', max_length=200)),
                ('tipo', models.CharField(blank=True, default='', max_length=50)),
                ('dia_semana', models.CharField(blank=True, default='', max_length=50)),
                ('turno', models.CharField(blank=True, default='', max_length=20)),
                ('professor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atividades', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('parentesco', models.CharField(blank=True, default='', max_length=50)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('school', models.CharField(blank=True, default='', max_length=200)),
                ('serie', models.CharField(blank=True, default='', max_length=10)),
                ('turno', models.CharField(blank=True, default='', max_length=20)),
                ('health_problem', models.CharField(blank=True, default='', max_length=200)),
                ('status_lsd', models.CharField(blank=True, default='', max_length=50)),
                ('activities', models.ManyToManyField(blank=True, to='AppLSD.activity')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alunos', to='AppLSD.family')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='alunos',
            field=models.ManyToManyField(related_name='atividades', to='AppLSD.aluno'),
        ),
        migrations.CreateModel(
            name='ChamadaAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('observacoes', models.TextField(blank=True)),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppLSD.activity')),
                ('responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChamadaTurma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('observacoes', models.TextField(blank=True)),
                ('professor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FrequenciaAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presente', models.BooleanField(default=True)),
                ('motivo_falta', models.CharField(blank=True, max_length=100)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppLSD.aluno')),
                ('chamada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas', to='AppLSD.chamadaturma')),
            ],
        ),
        migrations.CreateModel(
            name='FrequenciaAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presente', models.BooleanField(default=True)),
                ('motivo_falta', models.CharField(blank=True, max_length=100)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppLSD.aluno')),
                ('chamada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas', to='AppLSD.chamadaatividade')),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sala', models.CharField(max_length=100)),
                ('turno', models.CharField(max_length=50)),
                ('professor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turmas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='chamadaturma',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppLSD.turma'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alunos', to='AppLSD.turma'),
        ),
    ]
