# Generated by Django 5.2.7 on 2025-10-19 23:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(default='', max_length=100)),
                ('responsible_name', models.CharField(default='', max_length=255)),
                ('nis', models.CharField(blank=True, max_length=20, null=True)),
                ('rg', models.CharField(blank=True, max_length=20, null=True)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, max_length=10, null=True)),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('neighborhood', models.CharField(default='Não informado', max_length=100)),
                ('reference_point', models.CharField(blank=True, max_length=200, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('marital_status', models.CharField(choices=[('solteira', 'Solteira'), ('casada', 'Casada'), ('separada', 'Separada'), ('viuva', 'Viúva'), ('divorciada', 'Divorciada'), ('uniao_estavel', 'União Estável'), ('convive', 'Convive com Alguém'), ('outro', 'Outro')], default='Escolha o estado civi', max_length=30, verbose_name='Estado Civil')),
                ('education', models.CharField(choices=[('analfabeto', 'Analfabeto'), ('fund_comp', 'Ens. Fund. Comp.'), ('fund_incomp', 'Ens. Fund. Incomp.'), ('med_comp', 'Ens. Med. Comp.'), ('med_incomp', 'Ens. Med. Incomp.'), ('sup_comp', 'Ens. Sup. Comp.'), ('sup_incomp', 'Ens. Sup. Incomp.')], default='Escolha a escolaridade', max_length=50, verbose_name='Escolaridade')),
                ('race', models.CharField(blank=True, choices=[('branco', 'Branco'), ('preto', 'Preto'), ('pardo', 'Pardo'), ('amarelo', 'Amarelo'), ('indigena', 'Indígena')], default='Escolha a raça', max_length=30, null=True, verbose_name='Raça')),
                ('religion', models.CharField(blank=True, choices=[('catolico', 'Católico'), ('evangelico', 'Evangélico'), ('espirita', 'Espírita'), ('matriz_africana', 'Matriz Africana'), ('nao_possui', 'Não possui religião')], default='Escolha a religião', max_length=50, null=True, verbose_name='Religião')),
                ('social_benefits', models.JSONField(blank=True, default=list)),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('is_working', models.BooleanField(default=False)),
                ('working_function', models.CharField(blank=True, max_length=100, null=True)),
                ('working_location', models.CharField(blank=True, max_length=100, null=True)),
                ('has_proven_income', models.BooleanField(default=False)),
                ('income_types', models.JSONField(blank=True, default=list)),
                ('salary_range', models.CharField(blank=True, choices=[('1_sm', '1 Salário Mínimo'), ('2_sm', '2 Salários Mínimos')], max_length=30, null=True)),
                ('others_contribute', models.BooleanField(default=False)),
                ('who_contributes', models.CharField(blank=True, max_length=100, null=True)),
                ('domicile_type', models.CharField(blank=True, choices=[('proprio', 'Próprio'), ('alugado', 'Alugado'), ('cedido', 'Cedido')], max_length=10, null=True)),
                ('num_residents', models.IntegerField(default=0)),
                ('has_elderly', models.BooleanField(default=False)),
                ('has_adolescent', models.BooleanField(default=False)),
                ('has_child', models.BooleanField(default=False)),
                ('has_pregnant', models.BooleanField(default=False)),
                ('file_info', models.FileField(blank=True, null=True, upload_to='families_docs/')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, default='', max_length=200)),
                ('tipo', models.CharField(blank=True, default='', max_length=50)),
                ('dia_semana', models.CharField(blank=True, default='', max_length=50)),
                ('turno', models.CharField(blank=True, default='', max_length=20)),
                ('professor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atividades', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('parentesco', models.CharField(blank=True, default='', max_length=50)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('school', models.CharField(blank=True, default='', max_length=200)),
                ('serie', models.CharField(blank=True, default='', max_length=10)),
                ('turno', models.CharField(blank=True, default='', max_length=20)),
                ('health_problem', models.CharField(blank=True, default='', max_length=200)),
                ('status_lsd', models.CharField(blank=True, default='', max_length=50)),
                ('activities', models.ManyToManyField(blank=True, to='AppLSD.activity')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alunos', to='AppLSD.family')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='alunos',
            field=models.ManyToManyField(related_name='atividades', to='AppLSD.aluno'),
        ),
        migrations.CreateModel(
            name='Adult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('parentesco', models.CharField(blank=True, default='', max_length=50)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('school_level', models.CharField(max_length=50)),
                ('ocupacao', models.CharField(max_length=100)),
                ('renda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=50)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adults', to='AppLSD.family')),
            ],
        ),
        migrations.CreateModel(
            name='FrequenciaAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, null=True)),
                ('presente', models.BooleanField(default=True)),
                ('aluno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppLSD.aluno')),
                ('atividade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppLSD.activity')),
            ],
        ),
        migrations.CreateModel(
            name='FrequenciaTurma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, null=True)),
                ('presente', models.BooleanField(default=True)),
                ('aluno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppLSD.aluno')),
            ],
        ),
        migrations.CreateModel(
            name='FrequenciaAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presente', models.BooleanField(default=True)),
                ('motivo_falta', models.CharField(blank=True, max_length=100)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppLSD.aluno')),
                ('chamada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas', to='AppLSD.frequenciaturma')),
            ],
        ),
        migrations.CreateModel(
            name='OcorrenciaAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('tipo', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('responsavel', models.CharField(blank=True, max_length=100)),
                ('observacoes', models.TextField(blank=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias', to='AppLSD.aluno')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('admin', 'Admin'), ('coordenação', 'Coordenação'), ('supervisor', 'Supervisor'), ('professor', 'Professor'), ('administrativo', 'Administrativo'), ('colaborador', 'Colaborador')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faixa_etaria', models.CharField(choices=[('06-07 anos', '06 a 07 anos'), ('08-09 anos', '08 a 09 anos'), ('10-12 anos', '10 a 12 anos'), ('13-17 anos', '13 a 17 anos')], default='Selecione a faixa  etária', max_length=15, verbose_name='Faixa Etária')),
                ('sala', models.CharField(max_length=100)),
                ('turno', models.CharField(max_length=50)),
                ('ano_letivo', models.IntegerField(default=2025)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('professor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turmas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MovimentacaoTurmaAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_movimentacao', models.DateField(auto_now_add=True)),
                ('motivo', models.CharField(blank=True, max_length=200)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_turmas', to='AppLSD.aluno')),
                ('turma_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppLSD.turma')),
                ('turma_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='AppLSD.turma')),
            ],
        ),
        migrations.AddField(
            model_name='frequenciaturma',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppLSD.turma'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alunos', to='AppLSD.turma'),
        ),
    ]
