# Generated by Django 5.2.7 on 2025-10-20 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLSD', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='working_function',
        ),
        migrations.RemoveField(
            model_name='family',
            name='working_location',
        ),
        migrations.AddField(
            model_name='family',
            name='function',
            field=models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='family',
            name='social_benefits',
            field=models.CharField(blank=True, choices=[('bolsa_brasil', 'Programa Bolsa Brasil - PBF'), ('bpc', 'Benefício de Prestação Continuada - BPC'), ('cria_alagoana', 'Criança Alagoana - CRIA')], max_length=255, null=True, verbose_name='Programas Sociais'),
        ),
    ]
