# Generated by Django 5.2.7 on 2025-10-20 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLSD', '0002_remove_family_working_function_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='education',
            field=models.CharField(blank=True, choices=[('analfabeto', 'Analfabeto'), ('fund_comp', 'Ens. Fund. Comp.'), ('fund_incomp', 'Ens. Fund. Incomp.'), ('med_comp', 'Ens. Med. Comp.'), ('med_incomp', 'Ens. Med. Incomp.'), ('sup_comp', 'Ens. Sup. Comp.'), ('sup_incomp', 'Ens. Sup. Incomp.')], default='Escolha a escolaridade', max_length=50, null=True, verbose_name='Escolaridade'),
        ),
        migrations.AlterField(
            model_name='family',
            name='function',
            field=models.CharField(blank=True, default=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='family',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('solteira', 'Solteira'), ('casada', 'Casada'), ('separada', 'Separada'), ('viuva', 'Viúva'), ('divorciada', 'Divorciada'), ('uniao_estavel', 'União Estável'), ('convive', 'Convive com Alguém'), ('outro', 'Outro')], default='Escolha o estado civil', max_length=30, null=True, verbose_name='Estado Civil'),
        ),
        migrations.AlterField(
            model_name='family',
            name='sex',
            field=models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino')], default='Escolha o sexo', max_length=10, null=True, verbose_name='Sexo'),
        ),
    ]
