# Generated by Django 5.2.7 on 2025-10-20 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLSD', '0003_alter_family_education_alter_family_function_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='sex',
            field=models.CharField(blank=True, choices=[('', '---------'), ('Masculino', 'Masculino'), ('Feminino', 'Feminino')], default='Escolha o sexo', max_length=10, null=True, verbose_name='Sexo'),
        ),
    ]
