# Generated by Django 5.2.5 on 2025-09-30 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLSD', '0003_alter_activity_professor_perfilprofessor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frequenciaatividade',
            name='chamada',
        ),
        migrations.RemoveField(
            model_name='chamadaturma',
            name='professor',
        ),
        migrations.RemoveField(
            model_name='chamadaturma',
            name='turma',
        ),
        migrations.RemoveField(
            model_name='frequenciaatividade',
            name='motivo_falta',
        ),
        migrations.AddField(
            model_name='frequenciaatividade',
            name='atividade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppLSD.activity'),
        ),
        migrations.AddField(
            model_name='frequenciaatividade',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='frequenciaatividade',
            name='aluno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppLSD.aluno'),
        ),
        migrations.CreateModel(
            name='FrequenciaTurma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, null=True)),
                ('presente', models.BooleanField(default=True)),
                ('aluno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppLSD.aluno')),
                ('turma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppLSD.turma')),
            ],
        ),
        migrations.AlterField(
            model_name='frequenciaaluno',
            name='chamada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas', to='AppLSD.frequenciaturma'),
        ),
        migrations.DeleteModel(
            name='ChamadaAtividade',
        ),
        migrations.DeleteModel(
            name='ChamadaTurma',
        ),
    ]
