# Generated by Django 5.2.7 on 2025-10-21 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLSD', '0004_alter_family_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='cep',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP'),
        ),
    ]
