# Generated by Django 5.2.5 on 2025-10-06 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLSD', '0004_remove_frequenciaatividade_chamada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='file_info',
            field=models.FileField(blank=True, null=True, upload_to='families_docs/'),
        ),
    ]
