# Generated by Django 5.2.7 on 2025-10-23 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLSD', '0005_family_cep'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='is_benefits',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='family',
            name='telephone_2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='family',
            name='address',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='family',
            name='cep',
            field=models.CharField(max_length=9, null=True, verbose_name='CEP'),
        ),
    ]
