# Generated by Django 5.2.7 on 2025-10-23 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLSD', '0005_family_cep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='address',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='family',
            name='cep',
            field=models.CharField(max_length=9, null=True, verbose_name='CEP'),
        ),
    ]
