# Generated by Django 5.2.7 on 2025-10-13 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLSD', '0006_perfilusuario_delete_perfilprofessor'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='ano_letivo',
            field=models.IntegerField(default=2025),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='tipo',
            field=models.CharField(choices=[('admin', 'Admin'), ('coordenação', 'Coordenação'), ('supervisor', 'Supervisor'), ('professor', 'Professor'), ('administrativo', 'Administrativo'), ('colaborador', 'Colaborador')], max_length=20),
        ),
        migrations.CreateModel(
            name='MovimentacaoTurmaAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_movimentacao', models.DateField(auto_now_add=True)),
                ('motivo', models.CharField(blank=True, max_length=200)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_turmas', to='AppLSD.aluno')),
                ('turma_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppLSD.turma')),
                ('turma_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='AppLSD.turma')),
            ],
        ),
    ]
