# Generated by Django 5.2.7 on 2025-10-23 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLSD', '0006_family_is_benefits_family_telephone_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='social_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
