# Generated by Django 5.2.7 on 2025-10-13 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLSD', '0007_turma_ano_letivo_alter_perfilusuario_tipo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OcorrenciaAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('tipo', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('responsavel', models.CharField(blank=True, max_length=100)),
                ('observacoes', models.TextField(blank=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias', to='AppLSD.aluno')),
            ],
        ),
    ]
