# Generated by Django 5.2.7 on 2025-10-24 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLSD', '0007_family_social_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adult',
            name='social_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='family',
            name='birth_date',
            field=models.DateField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='family',
            name='cpf',
            field=models.CharField(blank=True, default='', max_length=14, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='family',
            name='nis',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='family',
            name='rg',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfis', to=settings.AUTH_USER_MODEL),
        ),
    ]
