# Generated by Django 5.2.7 on 2025-10-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLSD', '0008_adult_social_name_alter_family_birth_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adult',
            old_name='phone',
            new_name='telephone',
        ),
        migrations.RemoveField(
            model_name='adult',
            name='school_level',
        ),
        migrations.AddField(
            model_name='adult',
            name='education',
            field=models.CharField(blank=True, choices=[('analfabeto', 'Analfabeto'), ('fund_comp', 'Ens. Fund. Comp.'), ('fund_incomp', 'Ens. Fund. Incomp.'), ('med_comp', 'Ens. Med. Comp.'), ('med_incomp', 'Ens. Med. Incomp.'), ('sup_comp', 'Ens. Sup. Comp.'), ('sup_incomp', 'Ens. Sup. Incomp.')], default='Escolha a escolaridade', max_length=50, null=True, verbose_name='Escolaridade'),
        ),
        migrations.AddField(
            model_name='adult',
            name='sex',
            field=models.CharField(blank=True, choices=[('', '---------'), ('Masculino', 'Masculino'), ('Feminino', 'Feminino')], default='Escolha o sexo', max_length=15, null=True, verbose_name='Sexo'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='ensino',
            field=models.CharField(blank=True, choices=[('', '---------'), ('Fundamental_1', 'Ensino Fundamental 1'), ('Fundamental_2', 'Ensino Fundamental 2'), ('Médio', 'Ensino Médio')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='aluno',
            name='sex',
            field=models.CharField(blank=True, choices=[('', '---------'), ('Masculino', 'Masculino'), ('Feminino', 'Feminino')], default='Escolha o sexo', max_length=30, null=True, verbose_name='Sexo'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='special_need',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='health_problem',
            field=models.CharField(blank=True, choices=[('', '---------'), ('yes', 'Tem'), ('no', 'Não Tem')], default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='serie',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Série'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='status_lsd',
            field=models.CharField(blank=True, choices=[('', '---------'), ('ativo', 'Ativo'), ('inativo', 'Inativo'), ('Suspenso', 'Suspenso'), ('desligado', 'Desligado')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='turno',
            field=models.CharField(blank=True, choices=[('', '---------'), ('Matutino', 'Matutino'), ('Vespertino', 'Vespertino')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='family',
            name='salary_range',
            field=models.CharField(blank=True, choices=[('', '---------'), ('1_sm', '1 Salário Mínimo'), ('2_sm', '2 Salários Mínimos')], max_length=30, null=True),
        ),
    ]
