# Generated by Django 5.2.7 on 2025-10-15 16:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLSD', '0008_ocorrenciaaluno'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turma',
            name='faixa_etaria',
            field=models.CharField(choices=[('06-07', '06 a 07 anos'), ('08-09', '08 a 09 anos'), ('10-12', '10 a 12 anos'), ('13-17', '13 a 17 anos')], default='Selecione a faixa  etária', max_length=5, verbose_name='Faixa Etária'),
        ),
        migrations.AddField(
            model_name='turma',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
