# Generated by Django 5.2.7 on 2025-10-15 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLSD', '0009_turma_created_at_turma_faixa_etaria_turma_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='faixa_etaria',
            field=models.CharField(choices=[('06-07 anos', '06 a 07 anos'), ('08-09 anos', '08 a 09 anos'), ('10-12 anos', '10 a 12 anos'), ('13-17 anos', '13 a 17 anos')], default='Selecione a faixa  etária', max_length=15, verbose_name='Faixa Etária'),
        ),
    ]
