# Generated by Django 5.2.7 on 2025-10-24 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLSD', '0009_rename_phone_adult_telephone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='ensino',
            field=models.CharField(blank=True, choices=[('', '---------'), ('fundamental1', 'Ensino Fundamental 1'), ('fundamental2', 'Ensino Fundamental 2'), ('medio', 'Ensino Médio')], default='', max_length=100),
        ),
    ]
