# Generated by Django 5.2.7 on 2025-10-25 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLSD', '0010_alter_aluno_ensino'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='health_problem',
            field=models.CharField(blank=True, choices=[('', '---------'), ('yes', 'Sim'), ('no', 'Não')], default='', max_length=200),
        ),
    ]
