# Generated by Django 5.2.7 on 2025-10-25 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppLSD', '0006_alter_family_address_alter_family_cep'),
        ('AppLSD', '0010_alter_aluno_ensino'),
    ]

    operations = [
    ]
