# Generated by Django 5.2.7 on 2025-10-27 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLSD', '0011_alter_aluno_health_problem'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='has_pcd',
            field=models.BooleanField(default=False),
        ),
    ]
