# Generated by Django 5.2.7 on 2025-10-25 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppLSD', '0011_alter_aluno_health_problem'),
        ('AppLSD', '0011_merge_20251025_0009'),
    ]

    operations = [
    ]
