# Generated by Django 5.2.7 on 2025-10-27 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLSD', '0012_family_has_pcd'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='qual_medicacao',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='aluno',
            name='uso_medicacao',
            field=models.CharField(blank=True, choices=[('', '---------'), ('yes', 'Sim'), ('no', 'Não')], default='', max_length=200),
        ),
    ]
