# Generated by Django 5.2.7 on 2025-10-27 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLSD', '0013_aluno_qual_medicacao_aluno_uso_medicacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adult',
            name='ocupacao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='adult',
            name='renda',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='adult',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ocorrenciaaluno',
            name='tipo',
            field=models.CharField(blank=True, choices=[('', '---------'), ('Advertência', 'Advertência'), ('Atestado Médico', 'Atestado Médico'), ('Afastamento Atividades', 'Afastamentodas Atividades'), ('Desligamento', 'Desligamento'), ('Elogio', 'Elogio'), ('Suspensão', 'Suspensão'), ('Outro', 'Outro')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='turma',
            name='turno',
            field=models.CharField(blank=True, choices=[('', '---------'), ('Matutino', 'Matutino'), ('Vespertino', 'Vespertino')], default='', max_length=20),
        ),
    ]
