# Generated by Django 5.2.7 on 2025-10-27 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppLSD', '0012_merge_20251025_1933'),
        ('AppLSD', '0014_alter_adult_ocupacao_alter_adult_renda_and_more'),
    ]

    operations = [
    ]
