# Generated by Django 5.2.5 on 2025-10-31 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLSD', '0015_merge_20251031_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrenciaaluno',
            name='observacoes',
            field=models.CharField(blank=True, choices=[('', '---------'), ('Doença', 'Doença'), ('Indisciplina', 'Indisciplina'), ('Descumprimento das regras da instituição', 'Descumprimento das regras da instituição'), ('Falta', 'Falta'), ('Outro', 'Outro')], default='', max_length=100),
        ),
    ]
