# Generated by Django 5.2.5 on 2025-10-31 22:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLSD', '0016_alter_ocorrenciaaluno_observacoes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='turno',
            field=models.CharField(blank=True, choices=[('', '---------'), ('Matutino', 'Matutino'), ('Vespertino', 'Vespertino')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='tipo',
            field=models.CharField(choices=[('admin', 'Admin'), ('coordenação', 'Coordenação'), ('supervisor', 'Supervisor'), ('professor', 'Professor'), ('administrativo', 'Administrativo'), ('diretoria', 'Diretoria'), ('colaborador', 'Colaborador')], max_length=20),
        ),
        migrations.CreateModel(
            name='PerfilProfessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('atividade', 'Professor de Atividade'), ('turma', 'Professor de Turma')], max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
