# Generated by Django 5.2.5 on 2025-10-31 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLSD', '0017_alter_activity_turno_alter_perfilusuario_tipo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='professor',
            new_name='facilitador',
        ),
        migrations.RenameField(
            model_name='turma',
            old_name='professor',
            new_name='educadora',
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='tipo',
            field=models.CharField(choices=[('admin', 'Admin'), ('coordenação', 'Coordenação'), ('supervisor', 'Supervisor'), ('educadora', 'Educadora'), ('facilitador', 'Facilitador(a)'), ('administrativo', 'Administrativo'), ('diretoria', 'Diretoria'), ('colaborador', 'Colaborador')], max_length=20),
        ),
        migrations.DeleteModel(
            name='PerfilProfessor',
        ),
    ]
