# Generated by Django 5.2.5 on 2025-10-31 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLSD', '0018_rename_professor_activity_facilitador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='status',
            field=models.CharField(blank=True, choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], max_length=10, null=True),
        ),
    ]
