# Generated by Django 5.2.5 on 2025-11-01 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLSD', '0019_family_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='health_problem',
            field=models.CharField(blank=True, choices=[('', '---------'), ('sim', 'Sim'), ('nao', 'Não')], default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='uso_medicacao',
            field=models.CharField(blank=True, choices=[('', '---------'), ('sim', 'Sim'), ('nao', 'Não')], default='', max_length=200),
        ),
    ]
