# Generated by Django 5.2.5 on 2025-11-01 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLSD', '0020_alter_aluno_health_problem_alter_aluno_uso_medicacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='health_problem',
            field=models.CharField(blank=True, choices=[('', '---------'), ('yes', 'Sim'), ('no', 'Não')], default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='uso_medicacao',
            field=models.CharField(blank=True, choices=[('', '---------'), ('yes', 'Sim'), ('no', 'Não')], default='', max_length=200),
        ),
    ]
