# Generated by Django 5.2.5 on 2025-11-02 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLSD', '0021_alter_aluno_health_problem_alter_aluno_uso_medicacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='status_lsd',
            field=models.CharField(blank=True, choices=[('', '---------'), ('ativo', 'Ativo'), ('inativo', 'Inativo'), ('Suspenso', 'Suspenso'), ('desligado', 'Desligado')], default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='uso_medicacao',
            field=models.CharField(blank=True, choices=[('', '---------'), ('yes', 'Sim'), ('no', 'Não')], default='', max_length=10),
        ),
    ]
