# Generated by Django 5.2.5 on 2025-11-03 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLSD', '0022_alter_aluno_status_lsd_alter_aluno_uso_medicacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='health_problem',
            field=models.BooleanField(blank=True, choices=[(True, 'Sim'), (False, 'Não')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='uso_medicacao',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('não', 'Não')], default='', max_length=10),
        ),
    ]
