# Generated by Django 5.2.5 on 2025-11-03 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLSD', '0023_alter_aluno_health_problem_alter_aluno_uso_medicacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='health_problem',
            field=models.BooleanField(blank=True, choices=[('True', 'Sim'), ('False', 'Não')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='special_need',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
