# Generated by Django 5.2.5 on 2025-11-05 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLSD', '0024_alter_aluno_health_problem_alter_aluno_special_need'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='health_problem',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('não', 'Não')], default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='special_need',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
