# Generated by Django 5.2.5 on 2025-11-05 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLSD', '0025_alter_aluno_health_problem_alter_aluno_special_need'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='ensino',
            field=models.CharField(blank=True, choices=[('', 'Selecione o ensino'), ('fundamental1', 'Ensino Fundamental 1'), ('fundamental2', 'Ensino Fundamental 2'), ('medio', 'Ensino Médio')], default='', max_length=100),
        ),
    ]
