# Generated by Django 5.2.5 on 2025-11-05 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLSD', '0026_alter_aluno_ensino'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='has_proven_income',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('não', 'Não')], default='não', max_length=3),
        ),
        migrations.AlterField(
            model_name='family',
            name='is_benefits',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('não', 'Não')], default='não', max_length=3),
        ),
        migrations.AlterField(
            model_name='family',
            name='is_working',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('não', 'Não')], default='não', max_length=3),
        ),
        migrations.AlterField(
            model_name='family',
            name='others_contribute',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('não', 'Não')], default='não', max_length=3),
        ),
        migrations.AlterField(
            model_name='family',
            name='religion',
            field=models.CharField(blank=True, choices=[('catolico', 'Católico'), ('evangelico', 'Evangélico'), ('espirita', 'Espírita'), ('matriz_africana', 'Matriz Africana'), ('nao_possui', 'Não possui religião')], default='Escolha a religião', max_length=30, null=True, verbose_name='Religião'),
        ),
    ]
