# Generated by Django 5.2.5 on 2025-11-06 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLSD', '0027_alter_family_has_proven_income_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='has_adult',
            field=models.BooleanField(default=False),
        ),
    ]
