# Generated by Django 5.2.5 on 2025-11-06 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLSD', '0028_family_has_adult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='has_adolescent',
            field=models.IntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='family',
            name='has_adult',
            field=models.IntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='family',
            name='has_child',
            field=models.IntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='family',
            name='has_elderly',
            field=models.IntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='family',
            name='has_pcd',
            field=models.IntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='family',
            name='has_pregnant',
            field=models.IntegerField(default=False),
        ),
    ]
