# Generated by Django 5.2.7 on 2025-11-15 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLSD', '0029_alter_family_has_adolescent_alter_family_has_adult_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='descricao',
            new_name='atividade',
        ),
        migrations.AlterField(
            model_name='activity',
            name='turno',
            field=models.CharField(blank=True, choices=[('', '---------'), ('Matutino', 'Matutino'), ('Vespertino', 'Vespertino')], default='', max_length=50),
        ),
    ]
