# Generated by Django 5.2.7 on 2025-11-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLSD', '0030_rename_descricao_activity_atividade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='tipo',
            field=models.CharField(blank=True, choices=[('arte_cultura', 'Arte e Cultura'), ('educativa', 'Socioeducativa'), ('esporte', 'Esporte e Lazer'), ('tecnologia', 'Tecnologia')], default='', max_length=50),
        ),
    ]
