# Generated by Django 5.2.7 on 2025-11-18 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppLSD', '0015_merge_20251027_1831'),
        ('AppLSD', '0031_alter_activity_tipo'),
    ]

    operations = [
    ]
