# Generated by Django 5.2.7 on 2025-11-18 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLSD', '0032_merge_20251118_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='number',
            field=models.CharField(blank=True, default='S/N', max_length=10, null=True),
        ),
    ]
