# Generated by Django 5.2.7 on 2025-11-23 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLSD', '0033_family_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='tipo',
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='tipo_perfil',
            field=models.CharField(choices=[('admin', 'Admin'), ('coordenacao', 'Coordenação'), ('servicosocial', 'Serviço Social'), ('educadora', 'Educadora'), ('facilitador', 'Facilitador(a)'), ('administrativo', 'Administrativo'), ('diretoria', 'Diretoria'), ('colaborador', 'Colaborador'), ('financeiro', 'Financeiro'), ('nutricao', 'Nutrição')], default='colaborador', max_length=20),
        ),
    ]
