# Generated by Django 5.2.7 on 2025-11-23 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppLSD', '0034_remove_perfilusuario_tipo_perfilusuario_tipo_perfil'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfilusuario',
            options={'verbose_name': 'Perfil de Usuário', 'verbose_name_plural': 'Perfis de Usuários'},
        ),
    ]
