# Generated by Django 5.2.7 on 2025-12-01 19:54

import AppLSD.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLSD', '0037_adult_cpf_aluno_cpf_alter_family_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adult',
            name='cpf',
            field=models.CharField(blank=True, default='', max_length=14, null=True, validators=[AppLSD.validators.validate_cpf]),
        ),
    ]
