# Generated by Django 5.2.7 on 2025-12-04 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLSD', '0041_alter_aluno_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='motivo_desligamento',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='family',
            name='status',
            field=models.CharField(blank=True, choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('desligado', 'Desligado')], max_length=10, null=True),
        ),
    ]
