# Generated by Django 5.2.7 on 2025-12-04 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLSD', '0042_family_motivo_desligamento_alter_family_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='mae_solo',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('não', 'Não')], default='não', max_length=3),
        ),
    ]
