# Generated by Django 5.2.7 on 2025-12-04 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLSD', '0043_family_mae_solo'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='dias_semana',
            field=models.JSONField(blank=True, default=list, verbose_name='Dias da semana'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='frequencia_tipo',
            field=models.CharField(choices=[('diaria', 'Diariamente'), ('especificos', 'Dias específicos')], default='diaria', max_length=20, verbose_name='Tipo de frequência'),
        ),
        migrations.AlterField(
            model_name='family',
            name='registration_number',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
