# Generated by Django 5.2.7 on 2025-12-06 20:31

import AppLSD.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLSD', '0045_remove_turma_created_at_remove_turma_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adult',
            name='cpf',
            field=models.CharField(blank=True, default='', max_length=14, null=True, validators=[AppLSD.validators.validate_cpf]),
        ),
    ]
