# Generated by Django 5.2.7 on 2025-12-06 21:02

import AppLSD.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLSD', '0047_alter_aluno_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adult',
            name='cpf',
            field=models.CharField(blank=True, default='', max_length=14, null=True, unique=True, validators=[AppLSD.validators.validate_cpf]),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='cpf',
            field=models.CharField(blank=True, default='', max_length=14, null=True, unique=True, validators=[AppLSD.validators.validate_cpf]),
        ),
    ]
