# Generated by Django 5.2.7 on 2025-12-06 23:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLSD', '0048_alter_adult_cpf_alter_aluno_cpf'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TurmaLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('editado_em', models.DateTimeField(auto_now=True, verbose_name='Editado em')),
                ('excluido', models.BooleanField(default=False, verbose_name='Excluído')),
                ('excluido_em', models.DateTimeField(blank=True, null=True, verbose_name='Excluído em')),
                ('acao', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('editado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_editado', to=settings.AUTH_USER_MODEL, verbose_name='Editado por')),
                ('excluido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_excluido', to=settings.AUTH_USER_MODEL, verbose_name='Excluído por')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='AppLSD.turma')),
            ],
            options={
                'verbose_name': 'Log de Turma',
                'verbose_name_plural': 'Logs de Turmas',
            },
        ),
    ]
