# Generated by Django 5.2.7 on 2025-12-10 14:28

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLSD', '0050_applog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='frequenciaatividade',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 12, 10, 14, 28, 35, 947141, tzinfo=datetime.timezone.utc), verbose_name='Criado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='frequenciaatividade',
            name='editado_em',
            field=models.DateTimeField(auto_now=True, verbose_name='Editado em'),
        ),
        migrations.AddField(
            model_name='frequenciaatividade',
            name='editado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_editado', to=settings.AUTH_USER_MODEL, verbose_name='Editado por'),
        ),
        migrations.AddField(
            model_name='frequenciaatividade',
            name='excluido',
            field=models.BooleanField(default=False, verbose_name='Excluído'),
        ),
        migrations.AddField(
            model_name='frequenciaatividade',
            name='excluido_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Excluído em'),
        ),
        migrations.AddField(
            model_name='frequenciaatividade',
            name='excluido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_excluido', to=settings.AUTH_USER_MODEL, verbose_name='Excluído por'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='cpf',
            field=models.CharField(blank=True, default='', max_length=14, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='frequenciaatividade',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AlterUniqueTogether(
            name='frequenciaatividade',
            unique_together={('atividade', 'aluno', 'data')},
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino')], max_length=1)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True)),
                ('rg', models.CharField(blank=True, max_length=20, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('neighborhood', models.CharField(blank=True, max_length=120, null=True)),
                ('cep', models.CharField(blank=True, max_length=10, null=True)),
                ('reference_point', models.CharField(blank=True, max_length=255, null=True)),
                ('schooling', models.CharField(blank=True, max_length=50, null=True)),
                ('occupation', models.CharField(blank=True, max_length=120, null=True)),
                ('income_type', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='AppLSD.family')),
            ],
        ),
        migrations.AddField(
            model_name='adult',
            name='person',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppLSD.person'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='person',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppLSD.person'),
        ),
    ]
