# Generated by Django 5.2.7 on 2025-12-12 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLSD', '0051_frequenciaatividade_criado_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='families_responsible', to='AppLSD.person'),
        ),
    ]
