# Generated by Django 5.2.7 on 2025-12-13 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLSD', '0052_family_responsible'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='profission',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
