# Generated by Django 5.2.7 on 2025-12-13 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppLSD', '0053_person_profission'),
    ]

    operations = [
    ]
