# Generated by Django 5.2.7 on 2025-12-13 21:04

from django.db import migrations

def forwards(apps, schema_editor):
    Person = apps.get_model('AppLSD', 'Person')
    Family = apps.get_model('AppLSD', 'Family')       # se existir
    Adult  = apps.get_model('AppLSD', 'Adult')        # se existir
    Aluno = apps.get_model('AppLSD', 'Aluno')     # se existir

    # Exemplo: responsável da família
    for fam in Family.objects.all():
        Person.objects.get_or_create(
            full_name=fam.responsible_name,
            defaults={
                'rg': fam.rg,
                'cpf': fam.cpf,
                'birth_date': fam.birth_date,
                'gender': fam.sex,
                'phone': fam.telephone,
                'address': fam.address,
                'neighborhood': fam.neighborhood,
                'cep': fam.cep,
                'profission': fam.occupation,
            }
        )

    # Adultos
    for adult in Adult.objects.select_related('family').all():
        fam = adult.family
        Person.objects.get_or_create(
            full_name=adult.name,
            defaults={
                'cpf': adult.cpf,
                'birth_date': adult.birth_date,
                'gender': adult.sex,
                'phone': adult.telephone,
                'address': fam.address if fam else '',
                'neighborhood': fam.neighborhood if fam else '',
                'cep': fam.cep if fam else '',
                'profission': adult.ocupacao,
            }
        )

    # Alunos
    for aluno in Aluno.objects.select_related('family').all():
        Person.objects.get_or_create(
            full_name=aluno.name,
            defaults={

                'cpf': aluno.cpf,
                'birth_date': aluno.birth_date,
                'gender': aluno.sex,
                'phone': aluno.family.telephone,
                'address': aluno.family.address,
                'neighborhood': aluno.family.neighborhood,
                'cep': aluno.family.cep,
                'profission': 'Assistido Escolar',
            }
        )

def backwards(apps, schema_editor):
    # normalmente pode deixar vazio ou remover só o que foi criado
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('AppLSD', '0054_populate_person_from_old_models'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
