# Generated by Django 5.2.7 on 2025-12-23 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLSD', '0055_populate_person_from_old_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='domicile_type',
            field=models.CharField(blank=True, choices=[('proprio', 'Próprio'), ('alugado', 'Alugado'), ('cedido', 'Cedido')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='family',
            name='sex',
            field=models.CharField(blank=True, choices=[('', '---------'), ('Masculino', 'Masculino'), ('Feminino', 'Feminino')], default='Escolha o sexo', max_length=15, null=True, verbose_name='Sexo'),
        ),
    ]
