# Generated by Django 5.2.7 on 2025-12-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLSD', '0056_alter_family_domicile_type_alter_family_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adult',
            name='sex',
            field=models.CharField(blank=True, choices=[('', '---------'), ('Masculino', 'Masculino'), ('Feminino', 'Feminino')], default='Escolha o sexo', max_length=10, null=True, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='sex',
            field=models.CharField(blank=True, choices=[('', '---------'), ('Masculino', 'Masculino'), ('Feminino', 'Feminino')], default='Escolha o sexo', max_length=10, null=True, verbose_name='Sexo'),
        ),
    ]
