# Generated by Django 5.2.7 on 2025-12-26 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLSD', '0057_alter_adult_sex_alter_aluno_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='education',
            field=models.CharField(blank=True, choices=[('Analfabeto', 'Analfabeto'), ('Ens. Fund. Comp.', 'Ens. Fund. Comp.'), ('Ens. Fund. Incomp.', 'Ens. Fund. Incomp.'), ('Ens. Med. Comp.', 'Ens. Med. Comp.'), ('Ens. Med. Incomp.', 'Ens. Med. Incomp.'), ('Ens. Sup. Comp.', 'Ens. Sup. Comp.'), ('Ens. Sup. Incomp.', 'Ens. Sup. Incomp.')], default='Escolha a escolaridade', max_length=50, null=True, verbose_name='Escolaridade'),
        ),
        migrations.AlterField(
            model_name='family',
            name='has_proven_income',
            field=models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=3),
        ),
        migrations.AlterField(
            model_name='family',
            name='is_benefits',
            field=models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=3),
        ),
        migrations.AlterField(
            model_name='family',
            name='is_working',
            field=models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=3),
        ),
        migrations.AlterField(
            model_name='family',
            name='mae_solo',
            field=models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], default='não', max_length=3),
        ),
        migrations.AlterField(
            model_name='family',
            name='others_contribute',
            field=models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], default='não', max_length=3),
        ),
        migrations.AlterField(
            model_name='family',
            name='race',
            field=models.CharField(blank=True, choices=[('Branco', 'Branco'), ('Preto', 'Preto'), ('Pardo', 'Pardo'), ('Amarelo', 'Amarelo'), ('Indígena', 'Indígena')], default='Escolha a raça', max_length=30, null=True, verbose_name='Raça'),
        ),
        migrations.AlterField(
            model_name='family',
            name='religion',
            field=models.CharField(blank=True, choices=[('Católico', 'Católico'), ('Evangélico', 'Evangélico'), ('Espírita', 'Espírita'), ('Matriz Africana', 'Matriz Africana'), ('Não possui religião', 'Não possui religião')], default='Escolha a religião', max_length=30, null=True, verbose_name='Religião'),
        ),
        migrations.AlterField(
            model_name='family',
            name='social_benefits',
            field=models.CharField(blank=True, choices=[('Programa Bolsa Família - PBF', 'Programa Bolsa Família - PBF'), ('Auxílio Brasil', 'Auxílio Brasil'), ('Benefício de Prestação Continuada - BPC', 'Benefício de Prestação Continuada - BPC'), ('Criança Alagoana - CRIA', 'Criança Alagoana - CRIA')], max_length=255, null=True, verbose_name='Programas Sociais'),
        ),
    ]
