# Generated by Django 5.2.7 on 2025-12-27 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLSD', '0058_alter_family_education_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='others_contribute',
            field=models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=3),
        ),
    ]
