# Generated by Django 5.2.7 on 2026-01-04 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLSD', '0060_alter_aluno_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='ano_letivo',
            field=models.IntegerField(default=2026),
        ),
    ]
