# Generated by Django 5.2.7 on 2026-01-05 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLSD', '0061_alter_turma_ano_letivo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='family',
            old_name='function',
            new_name='location',
        ),
        migrations.AddField(
            model_name='aluno',
            name='nis',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='family',
            name='gestante',
            field=models.CharField(blank=True, choices=[('', '---------'), ('Sim', 'Sim'), ('Não', 'Não'), ('Nutriz', 'Nutriz')], default='Está gestante?', max_length=15),
        ),
        migrations.AddField(
            model_name='family',
            name='nome_contato',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='family',
            name='nome_contato_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='status_lsd',
            field=models.CharField(blank=True, choices=[('', '---------'), ('Frequentando', 'Frequentando'), ('desligado', 'Desligado')], default='', max_length=15),
        ),
    ]
