# Generated by Django 5.2.7 on 2026-01-05 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLSD', '0062_rename_function_family_location_aluno_nis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='social_benefits',
            field=models.CharField(blank=True, choices=[('Programa Bolsa Família - PBF', 'Programa Bolsa Família - PBF'), ('Benefício de Prestação Continuada - BPC', 'Benefício de Prestação Continuada - BPC'), ('Criança Alagoana - CRIA', 'Criança Alagoana - CRIA')], max_length=255, null=True, verbose_name='Programas Sociais'),
        ),
    ]
