# Generated by Django 5.2.7 on 2026-01-06 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLSD', '0063_alter_family_social_benefits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='gestante',
            field=models.CharField(blank=True, choices=[('', '---------'), ('Sim', 'Sim'), ('Não', 'Não'), ('Nutriz', 'Nutriz')], default='', max_length=15),
        ),
    ]
