# Generated by Django 5.2.7 on 2026-01-08 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLSD', '0064_alter_family_gestante'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='aluguel_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Valor do aluguel'),
        ),
        migrations.AddField(
            model_name='family',
            name='bolsa_familia_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Valor do Bolsa Família'),
        ),
    ]
