# Generated by Django 5.2.7 on 2026-01-09 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLSD', '0065_family_aluguel_value_family_bolsa_familia_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adult',
            name='status',
            field=models.CharField(blank=True, choices=[('trabalha', 'Trabalha'), ('nao_trabalha', 'Não Trabalha'), ('faz_bico', 'Faz Bico'), ('autonomo', 'Autônomo')], max_length=50, null=True),
        ),
    ]
