# Generated by Django 5.2.7 on 2026-01-09 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLSD', '0066_alter_adult_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='ensino',
            field=models.CharField(blank=True, choices=[('', 'Selecione o ensino'), ('creche', 'Creche'), ('fundamental1', 'Ensino Fundamental 1'), ('fundamental2', 'Ensino Fundamental 2'), ('medio', 'Ensino Médio')], default='', max_length=100),
        ),
    ]
