# Generated by Django 5.2.7 on 2026-01-13 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLSD', '0067_alter_aluno_ensino'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='ensino',
            field=models.CharField(blank=True, choices=[('', 'Selecione o ensino'), ('infantil', 'Ensino Infantil'), ('fundamental1', 'Ensino Fundamental 1'), ('fundamental2', 'Ensino Fundamental 2'), ('medio', 'Ensino Médio')], default='', max_length=100),
        ),
    ]
