# Generated by Django 5.2.7 on 2026-01-13 03:02

import AppLSD.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLSD', '0068_alter_aluno_ensino'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='cpf',
            field=models.CharField(blank=True, default='', max_length=14, null=True, validators=[AppLSD.validators.validate_cpf]),
        ),
    ]
