# Generated by Django 5.2.7 on 2026-01-13 15:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLSD', '0069_alter_aluno_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='social_benefits',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Programa Bolsa Família - PBF', 'Programa Bolsa Família - PBF'), ('Benefício de Prestação Continuada - BPC', 'Benefício de Prestação Continuada - BPC'), ('Criança Alagoana - CRIA', 'Criança Alagoana - CRIA')], max_length=50), blank=True, default=list, size=None, verbose_name='Programas Sociais'),
        ),
    ]
