# Generated by Django 5.2.7 on 2026-01-13 22:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLSD', '0070_alter_family_social_benefits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='has_adolescent',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Adolescente'),
        ),
        migrations.AlterField(
            model_name='family',
            name='has_adult',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Adulto'),
        ),
        migrations.AlterField(
            model_name='family',
            name='has_child',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Criança'),
        ),
        migrations.AlterField(
            model_name='family',
            name='has_elderly',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Idoso'),
        ),
        migrations.AlterField(
            model_name='family',
            name='has_pcd',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='PCD'),
        ),
        migrations.AlterField(
            model_name='family',
            name='has_pregnant',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Gestante'),
        ),
        migrations.AlterField(
            model_name='family',
            name='num_residents',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantidade de Pessoas no Domicílio'),
        ),
    ]
