# Generated by Django 5.2.7 on 2026-01-13 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLSD', '0071_alter_family_has_adolescent_alter_family_has_adult_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='rede_ensino',
            field=models.CharField(blank=True, choices=[('municipal', 'Municipal'), ('estadual', 'Estadual')], default='', max_length=20),
        ),
    ]
