# Generated by Django 5.2.7 on 2026-01-14 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppLSD', '0073_converter_social_benefits_para_array'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfilusuario',
            old_name='tipo_perfil',
            new_name='PERFIL_TO_GROUP',
        ),
    ]
