# Generated by Django 5.2.7 on 2026-01-14 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppLSD', '0074_rename_tipo_perfil_perfilusuario_perfil_to_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfilusuario',
            old_name='PERFIL_TO_GROUP',
            new_name='tipo_perfil',
        ),
    ]
