# Generated by Django 5.2.7 on 2026-01-15 16:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLSD', '0075_rename_perfil_to_group_perfilusuario_tipo_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='motivo_desligamento',
        ),
        migrations.AlterField(
            model_name='family',
            name='has_adolescent',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Adolescente'),
        ),
        migrations.AlterField(
            model_name='family',
            name='has_adult',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Adulto'),
        ),
        migrations.AlterField(
            model_name='family',
            name='has_child',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Criança'),
        ),
        migrations.AlterField(
            model_name='family',
            name='has_elderly',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Idoso'),
        ),
        migrations.AlterField(
            model_name='family',
            name='has_pcd',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='PCD'),
        ),
        migrations.AlterField(
            model_name='family',
            name='has_pregnant',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Gestante'),
        ),
        migrations.AlterField(
            model_name='family',
            name='status',
            field=models.CharField(blank=True, choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], max_length=10, null=True),
        ),
    ]
