# Generated by Django 5.2.7 on 2026-01-17 19:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLSD', '0076_remove_family_motivo_desligamento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimentacaoturmaaluno',
            name='data_movimentacao',
        ),
        migrations.AddField(
            model_name='movimentacaoturmaaluno',
            name='data',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movimentacaoturmaaluno',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppLSD.aluno'),
        ),
        migrations.AlterField(
            model_name='movimentacaoturmaaluno',
            name='motivo',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='movimentacaoturmaaluno',
            name='turma_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='AppLSD.turma'),
        ),
        migrations.AlterField(
            model_name='movimentacaoturmaaluno',
            name='turma_origem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='AppLSD.turma'),
        ),
    ]
