# Generated by Django 5.2.7 on 2026-01-23 15:00

from datetime import time
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLSD', '0077_remove_movimentacaoturmaaluno_data_movimentacao_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='horario_fim',
            field=models.TimeField(default=time(0, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='horario_inicio',
            field=models.TimeField(default=time(0, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='turma',
            field=models.ForeignKey(
        on_delete=django.db.models.deletion.CASCADE,
        to='AppLSD.turma',
        ),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('editado_em', models.DateTimeField(auto_now=True, verbose_name='Editado em')),
                ('excluido', models.BooleanField(default=False, verbose_name='Excluído')),
                ('excluido_em', models.DateTimeField(blank=True, null=True, verbose_name='Excluído em')),
                ('acao', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('Activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='AppLSD.activity')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('editado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_editado', to=settings.AUTH_USER_MODEL, verbose_name='Editado por')),
                ('excluido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_excluido', to=settings.AUTH_USER_MODEL, verbose_name='Excluído por')),
            ],
            options={
                'verbose_name': 'Log de Atividade',
                'verbose_name_plural': 'Logs de Atividades',
            },
        ),
    ]
