# Generated by Django 5.2.7 on 2026-01-23 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppLSD', '0078_activity_horario_fim_activity_horario_inicio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='turma',
        ),
    ]
