# Generated by Django 5.2.7 on 2026-01-25 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLSD', '0079_remove_activity_turma'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoFamilia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('arquivo', models.FileField(upload_to='familias/documentos/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='AppLSD.family')),
            ],
        ),
    ]
