# Generated by Django 5.2.7 on 2026-01-25 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLSD', '0080_documentofamilia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentofamilia',
            name='arquivo',
            field=models.FileField(upload_to='families_docs/'),
        ),
    ]
