# Generated by Django 5.2.7 on 2026-01-26 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLSD', '0081_alter_documentofamilia_arquivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentofamilia',
            name='tipo',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documentofamilia',
            name='arquivo',
            field=models.FileField(upload_to='familias/%Y/%m/%d/'),
        ),
    ]
