# Generated by Django 5.2.7 on 2026-01-26 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLSD', '0082_documentofamilia_tipo_alter_documentofamilia_arquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentofamilia',
            name='tipo',
            field=models.CharField(default='geral', max_length=50),
        ),
    ]
