# Generated by Django 5.2.7 on 2026-01-26 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLSD', '0083_alter_documentofamilia_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='file_info',
            field=models.FileField(blank=True, null=True, upload_to='familias/%Y/%m/%d/'),
        ),
    ]
