# Generated by Django 5.2.7 on 2026-01-26 05:31
from django.db import migrations, models
from django.utils import timezone

def move_files(apps, schema_editor):
    Family = apps.get_model('AppLSD', 'Family')
    DocumentoFamilia = apps.get_model('AppLSD', 'DocumentoFamilia')

    ano_atual = timezone.now().year
    for family in Family.objects.exclude(file_info='').exclude(file_info__isnull=True):
        DocumentoFamilia.objects.create(
            family=family,
            ano=ano_atual,        # ou outro critério se você tiver
            tipo='migração',
            arquivo=family.file_info,
        )

class Migration(migrations.Migration):

    dependencies = [
        ('AppLSD', '0084_alter_family_file_info'),  # ajuste
    ]

    operations = [
        migrations.RunPython(move_files),
    ]



