# Generated by Django 5.2.7 on 2026-01-26 06:06
from django.db import migrations
from django.utils import timezone

def vincular_arquivos_antigos(apps, schema_editor):
    Family = apps.get_model('AppLSD', 'Family')
    DocumentoFamilia = apps.get_model('AppLSD', 'DocumentoFamilia')

    ano_atual = timezone.now().year

    for family in Family.objects.exclude(file_info='').exclude(file_info__isnull=True):
        # Se já tiver documento criado para esse arquivo, pule
        if DocumentoFamilia.objects.filter(family=family, arquivo=family.file_info.name).exists():
            continue

        DocumentoFamilia.objects.create(
            family=family,
            ano=ano_atual - 1,   # ou outro ano que faça sentido para “antigos”
            tipo='migração',
            arquivo=family.file_info,  # reaproveita o mesmo caminho em MEDIA
        )

class Migration(migrations.Migration):

    dependencies = [
        ('AppLSD', '0085_move_file_info_to_documentos'),
    ]

    operations = [
        migrations.RunPython(vincular_arquivos_antigos),
    ]

