# Generated by Django 5.2.7 on 2026-01-26 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLSD', '0086_vincular_arquivos_antigos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='file_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
