# Generated by Django 5.2.7 on 2026-01-28 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLSD', '0087_alter_family_file_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequenciaatividade',
            name='motivo_falta',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
