# Generated by Django 5.2.7 on 2026-01-29 21:11

import AppLSD.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLSD', '0088_frequenciaatividade_motivo_falta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adult',
            name='cpf',
            field=models.CharField(blank=True, default=None, max_length=14, null=True, unique=True, validators=[AppLSD.validators.validate_cpf]),
        ),
    ]
