# Generated by Django 5.2.7 on 2026-03-09 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLSD', '0089_alter_adult_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='grupo',
            field=models.CharField(blank=True, choices=[('', '---------'), ('Grupo Criança Feliz', 'Grupo Criança Feliz'), ('Grupo Primeira Infância', 'Grupo Primeira Infância'), ('Grupo Brincar e Aprender', 'Grupo Brincar e Aprender'), ('Grupo Pequenos Aventureiros', 'Grupo Pequenos Aventureiros'), ('Grupo Pequenos Talentos', 'Grupo Pequenos Talentos'), ('Grupo Crescer e Desenvolver', 'Grupo Crescer e Desenvolver'), ('Grupo Jovens Criativos', 'Grupo Jovens Criativos'), ('Grupo Jovens Sonhadores', 'Grupo Jovens Sonhadores'), ('Grupo Pensando no Futuro', 'Grupo Pensando no Futuro'), ('Grupo Futuro Brilhante', 'Grupo Futuro Brilhante'), ('Grupo Nova Geração', 'Grupo Nova Geração')], max_length=100, null=True),
        ),
    ]
