# Generated by Django 5.2.7 on 2026-03-10 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLSD', '0090_turma_grupo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turma',
            name='sala',
        ),
        migrations.AlterField(
            model_name='turma',
            name='faixa_etaria',
            field=models.CharField(choices=[('06-07 anos', '06 a 07 anos'), ('08-09 anos', '08 a 09 anos'), ('08-10 anos', '08 a 10 anos'), ('10-12 anos', '10 a 12 anos'), ('13-14 anos', '13 a 14 anos'), ('13-17 anos', '13 a 17 anos'), ('15-17 anos', '15 a 17 anos')], default='Selecione a faixa  etária', max_length=15, verbose_name='Faixa Etária'),
        ),
    ]
