# Generated by Django 5.2.7 on 2026-05-20 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLSD', '0091_remove_turma_sala_alter_turma_faixa_etaria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequenciaaluno',
            name='motivo_falta',
            field=models.CharField(blank=True, choices=[('SJ', 'Sem Justificativa'), ('AM', 'Atestado Médico'), ('DM', 'Declaração Médica'), ('OT', 'Outro')], max_length=100),
        ),
    ]
