# Generated by Django 5.2.7 on 2026-06-20 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLSD', '0092_alter_frequenciaaluno_motivo_falta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='data_desligamento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data do desligamento'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='desligado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alunos_desligados', to=settings.AUTH_USER_MODEL, verbose_name='Desligado por'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='motivo_desligamento',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo do desligamento'),
        ),
    ]
