# Generated by Django 5.2.7 on 2026-06-20 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppLSD', '0093_aluno_data_desligamento_aluno_desligado_por_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='activities',
        ),
    ]
