# Generated by Django 5.2.7 on 2026-07-18 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLSD', '0094_remove_aluno_activities'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequenciaaluno',
            name='status',
            field=models.CharField(choices=[('P', 'Presente'), ('F', 'Falta'), ('NHA', 'Não houve aula')], default='P', max_length=3),
        ),
        migrations.AddField(
            model_name='frequenciaturma',
            name='motivo_nao_aula',
            field=models.CharField(blank=True, choices=[('FERIADO', 'Feriado'), ('EVENTO_EXTERNO', 'Evento externo'), ('FALTA_ENERGIA', 'Falta de energia'), ('SEM_AGUA', 'Sem água'), ('OUTRO', 'Outro')], max_length=30),
        ),
        migrations.AddField(
            model_name='frequenciaturma',
            name='observacao_nao_aula',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='frequenciaturma',
            name='status_aula',
            field=models.CharField(choices=[('NORMAL', 'Houve aula'), ('NAO_HOUVE', 'Não houve aula')], default='NORMAL', max_length=20),
        ),
    ]
