# Generated by Django 5.2.7 on 2026-07-19 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLSD', '0095_frequenciaaluno_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequenciaatividade',
            name='motivo_falta',
            field=models.CharField(blank=True, choices=[('SJ', 'Sem Justificativa'), ('AM', 'Atestado Médico'), ('DM', 'Declaração Médica'), ('OT', 'Outro')], max_length=100),
        ),
    ]
