# Generated by Django 5.2.7 on 2026-07-28 16:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLSD', '0096_alter_frequenciaatividade_motivo_falta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacaoturmaaluno',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_turma_criadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='movimentacaoturmaaluno',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes_turma', to='AppLSD.aluno'),
        ),
        migrations.AlterField(
            model_name='movimentacaoturmaaluno',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='movimentacaoturmaaluno',
            name='motivo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movimentacaoturmaaluno',
            name='turma_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_entrada', to='AppLSD.turma'),
        ),
        migrations.AlterField(
            model_name='movimentacaoturmaaluno',
            name='turma_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_saida', to='AppLSD.turma'),
        ),
    ]
